name: MinesweeperIPA
options:
  bundleIdPrefix: com.joeshu
packages: []
settings:
  base:
    PRODUCT_NAME: MinesweeperIPA
    IPHONEOS_DEPLOYMENT_TARGET: 16.0
targets:
  MinesweeperIPA:
    type: application
    platform: iOS
    sources:
      - Sources
      - Resources
    settings:
      base:
        INFOPLIST_FILE: Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.joeshu.MinesweeperIPA
        SWIFT_VERSION: 5.9
        TARGETED_DEVICE_FAMILY: 1,2
        SUPPORTS_MACCATALYST: NO
    scheme:
      testTargets: []
